#ifndef HELPER_H
#define HELPER_H
#include <ulfius.h>

#define API_PREFIX "/api"

#define API_ENDPOINT(METHOD, URL_FORMAT, CALLBACK) { #METHOD, API_PREFIX, URL_FORMAT, NULL, NULL, NULL, CALLBACK, NULL }

#define API_ENDPOINT_AUTH(METHOD, URL_FORMAT, CALLBACK, AUTH_CALLBACK) { #METHOD, API_PREFIX, URL_FORMAT, AUTH_CALLBACK, NULL, NULL, CALLBACK, NULL }

#endif
